---
title: "Assessing the Impact of Financial Assistances on Business and Income Outcomes: A Gender-Specific Analysis"
author: Dingning Li, Yiming Tang, Yingqi Pang 
abstract: "This study replicates and extends the investigation into the differential impacts of financial support on microenterprise performance, considering the gender of entrepreneurs. Analyzing data from 3,294 entrepreneurs, we explored the impact of loans, cash grants, and in-kind grants on business ownership, assets, and profitability, while accounting for personal characteristics. We found that all forms of financial support positively affect microenterprise growth, but in-kind grants are particularly beneficial, especially for female entrepreneurs. This research points to the importance of customizing financial interventions to consider gender, aiming to support economic empowerment and microenterprise resilience.
date: “`r format(Sys.time(), '%d %B %Y')`”
format: pdf
---

# Introduction

In the wake of global economic downturns, microenterprise development has gained attention for its critical role in bolstering grassroots economic resilience and empowerment. This sector's growth is influenced not only by the type of financial support it receives—commonly categorized as loans, cash grants, or in-kind grants—but also by the personal attributes of the enterprise owners. Earlier research, such as that by Field et al., has highlighted the potential of flexible microcredit arrangements to spur company growth [@field2013does], while Banerjee et al. have underscored personal characteristics like experience or optimism as key determinants of capital returns [@banerjee2019universal]. Nonetheless, debate persists regarding the most effective form of financial support for microenterprises. Taking a step further, the seminal study "Is It Who You Are or What You Get? Comparing the Impacts of Loans and Grants for Microenterprise Development" by Crépon, El Komi, and Osman, provided a randomized examination of 3294 entrepreneurs to assess the relative importance of financial support type versus owner characteristics in enterprise performance [@crepon2024you]. They reported that individual differences among owners could have more influence than the type of financial support received. Their work also suggested that, while all forms of support enhanced enterprise assets and profits, in-kind grants were particularly effective. However, it doesn’t justify any of the approaches to be the most effective, as there are many factors other than controlled variable, including ages and genders [@crepon2024you]. Therefore, this report only proves the existence of a correlation between the type of financial support and the business outcomes, but not a causal relationship. In our study, we utilized randomization on their experiment dataset to minimize the impact of irrelevant variables, enabling us to investigate which form of support yields the most significant impact on business outcomes. 

We replicate the paper by Bruno Crépon, Mohamed El Komi, and Adam Osman, focusing on the research question: Does the type of financial support have an impact on the overall performance of enterprises, and is this impact related to the gender of the entrepreneur? The three treatments are microcredit, in-kind grants, and cash grants. Our estimands quantify the expected impact of the type of financial support on our main variables:
- **Business Ownership**: Estimating the effect of financial support on the probability of owning a business post-intervention.
- **Monthly Expenses**: Assessing how different types of financial support influence the monthly expenses of businesses.
- **Monthly Profits**: Determining the role of financial support in enhancing business profitability.
- **Monthly Revenue**: Evaluating the impact of financial support on business sales activity.
- **New Assets**: Measuring the ability of financial support to enable businesses to acquire new assets post-intervention.
- **Labour Income**: Summing monthly profits, wages, and other labour income, providing a comprehensive view of the entrepreneur's earnings.
- **Total Income**: A broader measure of income that includes profits, rent, other incomes, government support, and transfers, offering a complete picture of the financial benefits of the intervention.

In this study, we will describe our experimental design and data collection methods in Data section, detailing the allocation of financial support types and the systematic tracking of growth indicators for microenterprises. Experiment section will provide an analytical narrative of our findings, showcasing the impact of microcredit, cash grants, and in-kind grants on the sustainability and expansion of businesses. We then delve into the gender-based differences in outcomes in Discussion section, uncovering significant insights into the variable effects of financial interventions. The concluding section will offer practical policy recommendations and propose directions for future research, underscoring the crucial role of customized financial strategies in supporting the success of microenterprises. 

The original research paper used Stata for data processing and analysis within its replication package. However, we opted for R [@citeR] to conduct all data organization and analysis. We used a suite of R libraries including `haven` [@haven] for reading Stata files, `readr` [@citereadr] for data import, `ggplot2` [@citeggplot2] for data visualization, `dplyr` [@citedplyr] for data manipulation, `knitr` [@citeknitr] for report generation, `kableExtra` [@citekableExtra] for table formatting, and `stargazer` [@stargazer] for creating regression tables. These libraries were selected for their functionality and compatibility with our dataset and analysis requirements.

# Experiment 
// TODO: Table 1: Baseline Balance of Variables Across Treatment Status

This experiment appears to have been designed to assess the influence of four treatments on a range of business-related outcomes. The process of randomization was employed to ensure that each participant in the experiment had an equal chance being assigned to any treatment groups. This methodological choice that facilitates the balancing of known and unknown mixing variables in these groups. Table 1 provided suggest that this randomization process was successful, as indicated by the balance check labeled “TRUE”. It confirms that the baseline characteristics were evenly distributed among the different treatment groups. This implies that any subsequent differences can be attributed to the effects of the treatments confidently rather than pre-existing differences among participants.


# Data Cleaning and Processing

Our data cleaning and processing workflow was designed to ensure that the dataset was robust and suitable for the statistical analysis required to answer our research questions. The R programming language [@citeR], along with a suite of packages including `haven` [@haven], `dplyr` [@citedplyr], `readr` [@citereadr], `ggplot2` [@citeggplot2], `knitr` [@citeknitr], `kableExtra` [@citekableExtra], and `stargazer` [@stargazer], was utilized for data manipulation and analysis. 

We began by loading the dataset from two Stata files using the `haven` package. The pre-intervention (`pre_data`) and post-intervention (`out_data`) data were both read and filtered to include only the entries that were present in both datasets, ensuring consistency and completeness for each subject across the study timeline.
A new dataset (`new_data`) was created to store the cleaned variables. We treated the `treatment_status` variable by creating dummy variables for each type of financial support, which were then bound to `new_data`. 
We defined several key outcome variables to assess the impact of the financial interventions:

## Outcome Variables

We assessed the impact of financial interventions using several outcome variables:
- **Business Ownership (`hasbiz`)**: A binary outcome variable indicating whether an entrepreneur owned a business. An individual does not have business if they do not have project or have no income source.
- **New Business Assets (`new_biz_assets`)**: A continuous variable representing the total value of new assets acquired by the business post-intervention. It is defined by the sum of inventory stocks, finished goods, liquid cash reserves, value of new business premises, recently purchased land, furniture, machinery and equipment, vehicles, and the cost of maintenance for these assets. 
- **Monthly Expenses**: A continuous variable summing all monthly costs incurred by the business. This reflects the immediate financial activity and potential expansion resulting from the intervention.
- **Monthly Profits (`monthly_profits`)**: Calculated as the difference between revenue and expenses, this variable measures the profitability of the business, a key indicator of financial viability.
- **Monthly Revenue (`monthly_revenue`)**: The total monthly sales before costs, representing the operational turnover and market activity of the business.

## Income Variables

We also computed income-related variables that aggregate various income sources:
- **Labour Income (`labour_inc`)**: It is calculated by summing the monthly profit, wage income, and other labour income source.
- **Total Income (`total_inc`)**: It is calculated by summing the monthly profit, wages, rental income from assets, other income streams not categorized as labor income, government support values, and received transfers.

These variables were chosen for their relevance to the business cycle and their potential to reflect the direct and indirect effects of financial support. Each measure is designed to capture different facets of business performance and growth, thereby providing a 
comprehensive view of the impact of financial assistance. 

We included several control variables to account for individual differences that might affect the outcomes. These included education level, age, marital status, previous employment, family income, migration desire, training received, and the presence of children. 

After cleaning, we performed regression analyses to understand the impact of financial interventions on business outcomes and income. The `lm` function in R was used to estimate the effects of microcredit, in-kind grants, and cash grants on various business and income outcomes. Custom functions were defined to streamline the regression analysis and visualization of results. 
The `regress` function was employed to carry out linear regressions for the treatment effects on specified outcome variables. Regression plots were saved as JPEG files, and regression tables were created in HTML format using the `stargazer` package.

To ensure that our treatment groups were comparable at baseline, we conducted a balance check. This involved regressing the treatment status on a set of pre-treatment covariates to confirm that the randomization process was successful. 

Throughout the data cleaning and processing stages, we paid meticulous attention to handling missing values, ensuring variable consistency, and maintaining the integrity of the results. Imputation and outlier detection were employed where appropriate, and our process was carefully documented to facilitate replication and validation of our findings. 


# Results

## Evaluating Financial Interventions on Business Outcomes

// TODO: Impacts fof Financial Supports on Business Outcomes

Table 2 provides a comprehensive summary of the business outcome for participants across different financial support programs: Micro Credit, In-Kind Grant, and Cash Grant. The table illustrates key financial indicators such as business ownership, acquisition of new assets, monthly expenditure, monthly revenue and monthly profit. Each entry is accompanied by standard errors in parentheses, offering insights into the variability and reliability of the observed data. The number of observations, denoted by N, stands at 3075 in total for each category, which indicates sample size for the analysis. The table summarize varied impacts of the different financial interventions on the economic activities of the participants. In the following discussion, we will examine the empirical data presented in Table1 for analyzing the effectiveness of these financial support mechanisms in contributing to the business outcomes. 

Starting with business ownership (Has Business), all illustrate in the first column indicates that none of Micro credit contribute to the increase in business ownership with a value of 0 with a standard error of 0.02. In contrast, In-Kind Grant shows a slight positive effect, with a 0.01 increase, and Cash Grant reflects a slight negative change, but the accompanying standard errors suggest that these changes are not statistically significant. In the domain of New Asset column, all interventions appear to associate with a decrease in assets, with Micro Credit recipients showing a notable reduction. These negative figures coupled with standard errors, suggest all three financial supports are statistically insignificant to result of asset acquisition. Both of the “Monthly Expenditure” column and the “Monthly Revenue” column depict a decrease across all groups of business outcomes, with largest decrease seen in the Cash Grant group for Monthly Expenditure and Micro Credit for Monthly Revenue. While it comes to “Monthly Profit”, In- Kind Grant shows an positive relationship with monthly profit once again, this could indicates that the recipients of In-Kind Grant are managing their resources more efficiently. 

Overall, the impacts of these financial interventions on business outcomes are nuanced. Particularly, the In-Kind Grant shows a potential for increasing profitability despite lower revenues, suggesting that the input of the grant may lead to more efficient business outcomes or cost savings. However, it is noticeable that the high standard error across the outcomes indicates the considerable variation within the sample. T-value calculated based on the given data, mostly reflects the result as statistically insignificant, which means that the data does not provide strong evidence that there is a true effect or different present, beyond what have occurred by random chance. Statistically insignificance does not necessarily indicate that there is no difference or that the effect does not exist. It may indicate that study did not have enough power due to missing considerations to detect an effect, or that the effect is smaller than what the study was designed to identify. 


## Gender-Specific Effects of Financial Interventions on Business Outcomes 

In the initial of our study, gender differences were not considered in our analytical framework; instead, we replicate the general conditions of financial support for our business performance investigation. During this phase of analytical study, we segregated the data by gender prior to examining the effects of Micro Credit, In-kind Grant, and Cash Grant on business-related outcomes we mentioned earlier. It becomes evident that incorporating gender as an independent factor could yield deeper insights. Consequently, we decided to differentiate the subsequent analysis by sex, hypothesizing that the influence of capital assistance might be affected significantly between male and female entrepreneurs as the conclusion of original articles. This approach aligns with the growing body of research emphasizing the importance of gender perspectives in economic studies, which often reveal differential impacts of financial assistances. 

//TODO: Table 3.1:  Impacts of Financial Supports on Business Outcomes Among Female Participants

The table summarizes the business outcome for female participation, illustrating a detailed impact of financial interventions, there is a marginal positive effect on the likelihood of having a business with Micro credit and In-kind Grant, while Cash Grant shows a slight negative influence. When looking at the acquisition of new assets, all these three financial supports are associated with significant negative impacts. Monthly expenditures also decreased across all types of financial aid, suggesting a reduction in business spending. Monthly profit shows a relatively small negative influence compared with New Asset for all financial assistance. Notably, only Monthly profit depict a positive change with the receipt of an In-Kind Grant, Micro Credit and Cash Grant, these effects are relatively small and less likely observed with other forms of capital assistance. This pattern highlights the complex relationship between the type of financial support and varied business outcomes among female leaders. 

//TODO: Table 3.2: Impacts of Financial Supports on Business Outcomes Among Male Participants
For the male participants in our study, the impact of various form of capital assistance displays the same complex pattern across different business outcomes. The likelihood of owning a business does not significantly change with the introduction of Micro Credit, In-Kind Grant, or Cash Grant, it’s evident by the negligible coefficients. However, positive performances are shown on the New Asset, with the latter showing a slightly larger effect on In-Kind Grant. Monthly Expenditure decreases significantly with all forms of capital assistance, which may indicate more efficient business operations or a reduction in business size or activity, which is similar with that of female participants. In terms of Monthly Revenue, we observed a decline with Micro Credit and a more obvious decline with Cash Grants, but there is only slight change with In-Kind Grants. Lastly, Monthly Profit does not show notable improvement with the capital assistance provided, although there is a insignificant trend towards reduced profits, particularly with Micro Credit and Cash Grants. 

## Divergent Effects on Male vs. Female Entrepreneurs 

//TODO: Figure 1: Female Monthly Profit vs. Male Monthly Profit

The comparison of graphical representations for the impact of capital assistance on monthly profit distinctly show that women have a more positive response than men. For female participants, the financial interventions, especially In-Kind Grant reflect the result in a clear increase in monthly profit, as indicates by the positive values above zero line. In contrast, the response from male participants to the same financial interventions show a more converse outcome, where the change in monthly profits does not show a consistent increase with coefficient below the zero line. The graphs indicates that the impact on men’s monthly profits does not present a similar positive trend as observed for women. Therefore, the data suggests that women experience a more positive performance of monthly profit from assistance compare to men. 

//TODO: Figure 1.2: Female New Asset vs. Male New Asset

Another notable business outcome is new asset acquisition present a obvious contrast between female and male participants. For female participants, the treatment groups, especially Cash Grant, are associated with a substantial decrease in New Asset, as indicated by the negative coefficient. Conversely, for male participants, the treatments appear to correlate with an increase in New Asset, with all treatment groups showing positive values. The comparison indicates the capital assistance translate into an increase in assets for male entrepreneurs more efficient than female entrepreneurs This difference underscores the distinct outcomes and potential uses for financial support between genders in the context of asset accumulation. 

Based on the visual data presented in the graphs for Monthly Profit and New Asset, it is apparent that female and male participants show different strengths across various business outcomes. While females show positive response in terms of Monthly Profit, indicating a beneficial use of capital in generating income, they seem to have a decrease in new asset acquisition when receiving financial assistance. In contrast, males demonstrate an increase in new asset acquisition with financial treatment, yet their monthly profits do not show the same level of clear positive impact as observed for females. Other business outcomes, where the data is not provided, are presumed to show no significant differences between females and males. This leads to the conclusion that there is no overall dominance in performance by one gender over the other across all assessed business outcomes. Both genders have areas where they excel and other areas where their performance is comparable. 

## Gender-Specific Effects of Financial Interventions on Income Outcome

//TODO: Table 4.1: Impacts of Financial Supports on Income Outcomes Among Female Participants

//TODO: Table 4.2: Impacts of Financial Supports on Income Outcomes Among Male Participants

Before we study the differential impact of financial support on Business Outcomes across genders, Income Outcomes is also a crucial for researching effective economic empowerment programs. Table 4.1 and Table 4.2 offers insight into gender-specific outcomes of three financial supports on income. The data can be analyzed to compare the influence affecting labor income and total income for female and male participants. For female participants, Both Cash Grant and In-Kind Grant appear to have the significant positive effect on both labor and total income, with more substantial effect by providing Cash Grant. Micro Credit, while showing a positive in labor income but converse effect on total income. On the male side, the effects of financial supports are less clear, with Micro Credit and In-Kind Grant associated with decrease in labor income and no clear pattern in total income. However, Cash Grant show a slight positive effect on labor income but a decrease in total income. 
If we compare the gender-specific effect, it seems that women benefit more from financial supports in terms of income outcomes. This aligns with the idea that women may perform between than men with these types of financial support when it comes to income outcomes. 

# Dicussion 

## What is the meaning of our research?"

According to our research, the effects of various financial support on business outcomes and income outcomes analyzed, indicating complex implications for economic activities and gender-specific responses. Financial support mechanisms may be adapted in light of our conclusions to address challenges and leverage the strengths of different population groups to ensure that economic programs are effective. The analysis of gender-specific data indicates that financial supports such as Micro Credit, In-Kind Grant, and Cash Grant produce various impacts on business for men and women. This result is crucial for considering gender in the design and implementation of such economic programs.

For example, the results show that certain forms of financial support, like In-Kind Grant can lead to increased profitability for women. It implies that financial resources are used more efficient and effective. But the same aid does not hold the same consequences across the board for men or when considering different forms of aid. Such differences underscore the potential for improved design in financial support policies or programs that account for these gender-specific responses. By doing so, programs can be modified for more directional and effective, aligning with the distinct needs of male and female. Therefore, it fosters and environment where economic growth and development are accessible to all genders. In addition, recognizing the different influence on asset acquisition and monthly profits between male and female, suggesting a reassessment of how financial support is allocated and managed. It calls for a strategic shift towards more detailed and targeted support. It might provide the idea of combination of grants, credit and other financial interventions, which support the diverse activities across genders.

In the end, the capacity of economic programs and business and income growth can be enhanced by embracing a more detailed understanding of how financial support affects various demographics, policymakers and practices to closing the gender gap in entrepreneurship.


## Weakness and Next Step 

The research presents a substantial limitation in its statistical findings, primarily that most data yield p-values less than 0.1. This threshold, while indicative of trends that merit further investigation, does not confer the statistical robustness required to make definitive claims. The results, therefore, should be interpreted with caution; they suggest potential patterns and effects that warrant attention but are not yet strong enough to confirm as conclusive outcomes. This nuance in the statistical significance underscores the preliminary nature of the findings and the necessity of further, more detailed research.  Another key limitation is the study's focus on short-term outcomes. The true test of financial interventions is their long-term sustainability and their capacity to support business growth and income stability over time. As such, there is a critical need for longitudinal studies that can provide a clearer picture of the enduring impacts of financial support on microenterprises. Furthermore, the study has not extensively examined the underlying causes behind the gender-specific responses to financial assistance. To design more effective support mechanisms, it's essential to delve into the social, cultural, and economic factors influencing these disparities. Additionally, the research design could benefit from incorporating a broader range of variables, such as the education level of entrepreneurs, their previous business experience, and their access to markets—all of which could significantly affect the outcomes of financial support. 

Future research should strive to collect more comprehensive data, potentially involving larger sample sizes or spanning longer periods, to achieve results with greater statistical significance. Such research could not only affirm the effectiveness of different types of financial support but also clarify the role gender plays in the development of microenterprises. Qualitative research could also enrich the understanding by capturing the subjective experiences of entrepreneurs and how they interact with various forms of financial assistance. 

## Ethic Concerns and Bias

The research of financial support and their impacts on business and income outcomes could raise potential biases and ethical concerns that might happened and need to be addressed to ensure the applicability of the research. Such biases can significantly affect the reliability of the results and conclusions. For example, sampling bias can occur if the individuals who participate into financial programs cannot be representative of the wider population. Another bias should be considered is responsive bias, which could reflect differences in how males and females perceive and report their successes that influenced by social expectations. It may lead collected data is skewed and not able to show the reliability. Additionally, the possibility of observer bias cannot be ignored. Data collectors’ preconceived perspectives of genders may influence their interpretation of information. Therefore, it is crucial to ensure the objectivity in data collection and interpretation. This includes employing careful sampling strategies, creating an environment that encourages fair access, using validated and unbiased data, and providing researchers with comprehensive training to recognize and mitigate their biases. In this way, research can more accurately reflect the true gender-specific impacts of financial interventions and contribute to the development of more effective economic support programs.

While addressing potential biases in our data collection is crucial for ensuring the validity and reality of our results, it is also important to focus on the ethical concerns to protect use of collected data and information. In any research, strict ethical standard governing the use of data are essential, especially those involving financial and personal outcomes. Participant privacy and the confidentiality of the information they provide must be maintained from the beginning of data collection through analysis and final results. It is a matter of trust that participants place in the research process and in the researchers themselves. Participants must be given clear and comprehensive information about how their data will be used, and researchers must be given informed consent that clarifies the scope of data application. This consent is a binding agreement, and any deviation from the specified use may constitute a breach of trust and may constitute a legal infringement.


# Conclusion: 

In the comprehensive analysis of microenterprise development, the study delves into the impact of different types of financial support—microcredit, in-kind grants, and cash grants—on business outcomes and income with a particular focus on gender-specific effects. It finds that while financial support, in general, has a positive effect on the performance of microenterprises, the nature of these effects varies significantly between male and female entrepreneurs. For female participants, in-kind grants show a consistent positive impact on monthly profits, indicating a potential for efficient resource management and an increase in profitability. However, both in-kind and cash grants lead to a significant decrease in new asset acquisition for women. This suggests that while these forms of support can enhance profitability, they may not necessarily translate into asset growth for female entrepreneurs. Male entrepreneurs, on the other hand, do not exhibit the same positive trends in monthly profits from financial interventions. However, there is evidence of an increase in new asset acquisition with financial treatment, pointing to a different pattern of financial support utilization between genders. When it comes to income outcomes, the study indicates that women benefit more from financial supports, especially cash grants, which significantly increase both labor and total income for female participants. For men, the effects are less pronounced, with no clear positive impact on total income and a mixed impact on labor income. The study underscores the complexity of the relationship between the type of financial support and business outcomes, emphasizing the need for gender-specific approaches in designing and implementing microenterprise development programs. 
